name: PluginDG
version: '${version}'
main: dev.canas.plugindg.PluginDG
api-version: 1.20
authors: [ CanasDev ]
description: Primeiro plugin do DG
depend:
  - CommandAPI
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.22"